// backend/utils/reportPdf.js
const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");

/**
 * Ensure uploads/reports exists
 */
function ensureReportsDir() {
  const reportsDir = path.join(__dirname, "..", "uploads", "reports");
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });
  return reportsDir;
}

function niceDate(dt) {
  try {
    if (!dt) return "";
    return new Date(dt).toLocaleString();
  } catch {
    return String(dt || "");
  }
}

function safeStr(v) {
  return v === null || v === undefined ? "" : String(v);
}

function addSectionTitle(doc, title) {
  doc.moveDown(0.6);
  doc.fontSize(14).font("Helvetica-Bold").text(title);
  doc.moveDown(0.2);
  doc
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor("#aaaaaa")
    .stroke();
  doc.moveDown(0.6);
}

function addKeyValue(doc, key, value) {
  doc.fontSize(10).font("Helvetica-Bold").text(`${key}: `, { continued: true });
  doc.font("Helvetica").text(safeStr(value));
}

function addBullets(doc, items = []) {
  if (!items.length) {
    doc.fontSize(10).font("Helvetica").text("—");
    return;
  }
  doc.fontSize(10).font("Helvetica");
  items.forEach((t) => doc.text(`• ${safeStr(t)}`));
}

function addTableLike(doc, rows = []) {
  // Simple text rows (not a real table)
  if (!rows.length) {
    doc.fontSize(10).font("Helvetica").text("—");
    return;
  }
  doc.fontSize(10).font("Helvetica");
  rows.forEach((r) => doc.text(r));
}

/**
 * Build PDF for a SINGLE CHILD report
 */
async function buildChildPdf({ pool, childId, meta = {} }) {
  // child
  const [[child]] = await pool.query(`SELECT * FROM children WHERE id=?`, [childId]);
  if (!child) throw new Error("Child not found");

  const childName = `${child.first_name || ""} ${child.middle_name ? child.middle_name + " " : ""}${child.last_name || ""}`.trim();

  // health records (latest 10)
  const [health] = await pool.query(
    `SELECT record_type, provider, record_date, notes, next_appointment
     FROM health_records
     WHERE child_id=?
     ORDER BY record_date DESC, id DESC
     LIMIT 10`,
    [childId]
  );

  // education summary
  const [[eduSum]] = await pool.query(
    `SELECT school, average_grade, honor
     FROM education_summaries
     WHERE child_id=?
     LIMIT 1`,
    [childId]
  );

  // education records (latest 10)
  const [edu] = await pool.query(
    `SELECT subject, grade, teacher, term, comments
     FROM education_records
     WHERE child_id=?
     ORDER BY id DESC
     LIMIT 10`,
    [childId]
  );

  // milestones (latest 10)
  const [miles] = await pool.query(
    `SELECT id, category, title, status, progress, target_date, last_updated
     FROM milestones
     WHERE child_id=?
     ORDER BY id DESC
     LIMIT 10`,
    [childId]
  );

  // milestone objectives
  const mileIds = miles.map((m) => m.id);
  let objectivesMap = new Map();
  if (mileIds.length) {
    const placeholders = mileIds.map(() => "?").join(",");
    const [objs] = await pool.query(
      `SELECT milestone_id, objective
       FROM milestone_objectives
       WHERE milestone_id IN (${placeholders})`,
      mileIds
    );
    for (const o of objs) {
      if (!objectivesMap.has(o.milestone_id)) objectivesMap.set(o.milestone_id, []);
      objectivesMap.get(o.milestone_id).push(o.objective);
    }
  }

  // Create PDF file
  const reportsDir = ensureReportsDir();
  const filename = `child_report_${childId}_${Date.now()}.pdf`;
  const absolutePath = path.join(reportsDir, filename);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const stream = fs.createWriteStream(absolutePath);
  doc.pipe(stream);

  // Header
  doc.fontSize(18).font("Helvetica-Bold").text("Single Child Report", { align: "left" });
  doc.moveDown(0.2);
  doc.fontSize(11).font("Helvetica").text(`Generated: ${new Date().toLocaleString()}`);
  if (meta.generatedByName) doc.text(`Generated by: ${meta.generatedByName} (${meta.generatedByRole || ""})`);
  doc.moveDown(0.8);

  addSectionTitle(doc, "Child Profile");
  addKeyValue(doc, "Name", childName);
  addKeyValue(doc, "Age", child.age);
  addKeyValue(doc, "Gender", child.gender);
  addKeyValue(doc, "Status", child.status);
  addKeyValue(doc, "Admission Date", child.admission_date ? new Date(child.admission_date).toISOString().slice(0, 10) : "");
  addKeyValue(doc, "House", child.house || "");
  addKeyValue(doc, "House Parent", child.house_parent || "");
  addKeyValue(doc, "Health Status", child.health_status || "");
  addKeyValue(doc, "Education Level", child.education_level || "");
  addKeyValue(doc, "Case Type", child.case_type || "");
  addKeyValue(doc, "Adoption Status", child.adoption_status || "");
  addKeyValue(doc, "Emergency Contact", child.emergency_contact || "");
  if (child.notes) addKeyValue(doc, "Notes", child.notes);

  addSectionTitle(doc, "Recent Health Records");
  addTableLike(
    doc,
    health.map((h) => {
      const rd = h.record_date ? new Date(h.record_date).toISOString().slice(0, 10) : "";
      const na = h.next_appointment ? new Date(h.next_appointment).toISOString().slice(0, 10) : "";
      return `• ${rd} | ${h.record_type} | ${h.provider} | Next: ${na} | ${safeStr(h.notes).slice(0, 120)}`;
    })
  );

  addSectionTitle(doc, "Education Summary");
  addKeyValue(doc, "School", eduSum?.school || "");
  addKeyValue(doc, "Average Grade", eduSum?.average_grade ?? "");
  addKeyValue(doc, "Honor", eduSum?.honor || "None");

  addSectionTitle(doc, "Recent Subject Records");
  addTableLike(
    doc,
    edu.map((e) => `• ${e.subject} | Grade: ${e.grade} | Teacher: ${e.teacher} | Term: ${e.term || ""} | ${safeStr(e.comments).slice(0, 80)}`)
  );

  addSectionTitle(doc, "Development Milestones (Recent)");
  miles.forEach((m) => {
    doc.fontSize(11).font("Helvetica-Bold").text(`${m.title} (${m.category})`);
    doc.fontSize(10).font("Helvetica").text(`Status: ${m.status} | Progress: ${m.progress}% | Target: ${m.target_date ? new Date(m.target_date).toISOString().slice(0, 10) : ""}`);
    doc.fontSize(10).font("Helvetica").text(`Last Updated: ${m.last_updated ? new Date(m.last_updated).toISOString().slice(0, 10) : ""}`);
    doc.moveDown(0.2);
    doc.fontSize(10).font("Helvetica-Bold").text("Objectives:");
    addBullets(doc, objectivesMap.get(m.id) || []);
    doc.moveDown(0.4);
  });

  doc.end();

  await new Promise((resolve, reject) => {
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  const st = fs.statSync(absolutePath);
  const fileSizeKb = Math.ceil(st.size / 1024);

  return {
    filename,
    absolutePath,
    fileSizeKb,
    title: `Single Child Report - ${childName}`,
    description: `Detailed report for ${childName} including profile, health, education, and milestones.`,
    category: "Children",
    subcategory: "Individual Reports",
    meta: { ...meta, childName },
  };
}

/**
 * Generic category PDFs (simple summary PDFs)
 */
async function buildCategoryPdf({ pool, reportKey, meta = {} }) {
  const reportsDir = ensureReportsDir();
  const filename = `${reportKey}_${Date.now()}.pdf`;
  const absolutePath = path.join(reportsDir, filename);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const stream = fs.createWriteStream(absolutePath);
  doc.pipe(stream);

  doc.fontSize(18).font("Helvetica-Bold").text("System Report", { align: "left" });
  doc.moveDown(0.2);
  doc.fontSize(11).font("Helvetica").text(`Report Key: ${reportKey}`);
  doc.text(`Generated: ${new Date().toLocaleString()}`);
  if (meta.generatedByName) doc.text(`Generated by: ${meta.generatedByName} (${meta.generatedByRole || ""})`);
  doc.moveDown(0.8);

  // Switch report type
  if (reportKey === "children_overview") {
    addSectionTitle(doc, "Children Overview");
    const [[tot]] = await pool.query(`SELECT COUNT(*) AS total FROM children`);
    const [byHouse] = await pool.query(
      `SELECT COALESCE(house,'(No House)') AS house, COUNT(*) AS c
       FROM children
       GROUP BY house
       ORDER BY c DESC`
    );
    addKeyValue(doc, "Total Children", tot.total);
    doc.moveDown(0.4);
    doc.fontSize(11).font("Helvetica-Bold").text("Children by House");
    addTableLike(doc, byHouse.map((r) => `• ${r.house}: ${r.c}`));
  }

  else if (reportKey === "development_overview") {
    addSectionTitle(doc, "Development Overview");
    const [[tot]] = await pool.query(`SELECT COUNT(*) AS total FROM milestones`);
    const [byStatus] = await pool.query(
      `SELECT status, COUNT(*) AS c
       FROM milestones
       GROUP BY status
       ORDER BY c DESC`
    );
    addKeyValue(doc, "Total Milestones", tot.total);
    doc.moveDown(0.4);
    doc.fontSize(11).font("Helvetica-Bold").text("Milestones by Status");
    addTableLike(doc, byStatus.map((r) => `• ${r.status}: ${r.c}`));
  }

  else if (reportKey === "donations_summary") {
    addSectionTitle(doc, "Donation Summary");
    const [[totals]] = await pool.query(
      `SELECT
        COALESCE(SUM(amount),0) AS totalAmount,
        COUNT(*) AS totalTransactions
      FROM donations
      WHERE status='Completed'`
    );
    addKeyValue(doc, "Total Amount", `PHP ${Number(totals.totalAmount).toFixed(2)}`);
    addKeyValue(doc, "Total Transactions", totals.totalTransactions);

    const [purposes] = await pool.query(
      `SELECT COALESCE(purpose,'Unspecified') AS purpose, COALESCE(SUM(amount),0) AS total
       FROM donations
       WHERE status='Completed'
       GROUP BY purpose
       ORDER BY total DESC
       LIMIT 10`
    );

    doc.moveDown(0.4);
    doc.fontSize(11).font("Helvetica-Bold").text("Top Purposes");
    addTableLike(doc, purposes.map((p) => `• ${p.purpose}: PHP ${Number(p.total).toFixed(2)}`));
  }

  else if (reportKey === "houses_overview") {
    addSectionTitle(doc, "Houses Overview");
    const [rows] = await pool.query(
      `SELECT COALESCE(house,'(No House)') AS house,
              COUNT(*) AS total,
              SUM(status='Active') AS activeCount,
              SUM(status<>'Active') AS nonActiveCount
       FROM children
       GROUP BY house
       ORDER BY total DESC`
    );

    addTableLike(
      doc,
      rows.map((r) => `• ${r.house}: total=${r.total}, active=${r.activeCount}, other=${r.nonActiveCount}`)
    );
  }

  else if (reportKey === "system_audit_summary") {
    addSectionTitle(doc, "System Audit Summary");
    const [[todayRow]] = await pool.query(
      `SELECT COUNT(*) AS todayCount
       FROM audit_trail
       WHERE DATE(created_at) = CURDATE()`
    );
    const [[criticalRow]] = await pool.query(
      `SELECT COUNT(*) AS criticalCount
       FROM audit_trail
       WHERE severity IN ('warning','error','critical')
         AND DATE(created_at) = CURDATE()`
    );

    addKeyValue(doc, "Today's Audit Entries", todayRow.todayCount);
    addKeyValue(doc, "Today's Critical Events", criticalRow.criticalCount);

    const [recent] = await pool.query(
      `SELECT created_at, user_name, user_role, action, module, details, severity
       FROM audit_trail
       ORDER BY created_at DESC, id DESC
       LIMIT 50`
    );

    doc.moveDown(0.4);
    doc.fontSize(11).font("Helvetica-Bold").text("Recent Activity (Last 50)");
    addTableLike(
      doc,
      recent.map((r) => `• ${niceDate(r.created_at)} | ${r.user_name} (${r.user_role}) | ${r.action} | ${r.module} | ${r.severity} | ${safeStr(r.details).slice(0, 80)}`)
    );
  }

  else {
    addSectionTitle(doc, "Report");
    doc.fontSize(10).font("Helvetica").text("No generator is configured for this report key.");
  }

  doc.end();

  await new Promise((resolve, reject) => {
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  const st = fs.statSync(absolutePath);
  const fileSizeKb = Math.ceil(st.size / 1024);

  // Map titles/descriptions per key
  const map = {
    children_overview: {
      title: "All Children Overview Report",
      description: "Summary of all children including demographics, health status, and placement.",
      category: "Children",
      subcategory: "Summary Reports",
    },
    development_overview: {
      title: "Overall Development Progress Report",
      description: "Comprehensive analysis of development milestones across all children.",
      category: "Development",
      subcategory: "Summary Reports",
    },
    donations_summary: {
      title: "Donation Summary Report",
      description: "Overview of donations including trends, top donors, and fund allocation.",
      category: "Financial",
      subcategory: "Donation Reports",
    },
    houses_overview: {
      title: "Houses Overview Report",
      description: "Summary of children per house including active/non-active counts.",
      category: "Houses",
      subcategory: "House Reports",
    },
    system_audit_summary: {
      title: "System Audit Summary Report",
      description: "Summary of audit activity and recent events.",
      category: "System",
      subcategory: "System Reports",
    },
  };

  const info = map[reportKey] || {
    title: `Report: ${reportKey}`,
    description: "Generated system report",
    category: "System",
    subcategory: "Reports",
  };

  return {
    filename,
    absolutePath,
    fileSizeKb,
    title: info.title,
    description: info.description,
    category: info.category,
    subcategory: info.subcategory,
    meta,
  };
}

module.exports = {
  buildChildPdf,
  buildCategoryPdf,
};
